
const STORAGE_KEY = "wrecklineSalvageUpgraded_v1";
const canvas = document.getElementById("game");
const ctx = canvas.getContext("2d");
const ui = {oxygen: oxygen, credits: credits, cargo: cargo, hull: hull, wave: wave, best: best, banner: banner, log: log, cargoUpgrade: cargoUpgrade, speedUpgrade: speedUpgrade, hullUpgrade: hullUpgrade};
let profile = loadProfile();
let run = null;
let keys = {};
function loadProfile(){const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):{credits:0,bestRun:0,upgrades:{cargo:1,speed:1,hull:1}}}
function saveProfile(){localStorage.setItem(STORAGE_KEY,JSON.stringify(profile))}
function logEvent(text,type="warn"){const row=document.createElement("div");row.className="history-item";row.innerHTML=`<div>${text}</div><div class="history-badge ${type}">${type.toUpperCase()}</div>`;ui.log.prepend(row);while(ui.log.children.length>12)ui.log.removeChild(ui.log.lastChild)}
function startRun(){run={active:true,player:{x:360,y:340,size:20,speed:2.6+(profile.upgrades.speed-1)*0.45},oxygen:100,hull:4+(profile.upgrades.hull-1)*2,hullMax:4+(profile.upgrades.hull-1)*2,cargoHeld:0,cargoMax:3+(profile.upgrades.cargo-1),wave:1,ticks:0,scrap:[],drones:[],stars:Array.from({length:80},()=>({x:Math.random()*720,y:Math.random()*420,r:Math.random()*2}))};ui.banner.className="result-banner neutral";ui.banner.textContent="Run active. Collect scrap and bank it before your hull gives out.";logEvent("New salvage run launched.","good");renderHud()}
function spawnScrap(){run.scrap.push({x:20+Math.random()*680,y:-20,size:14,value:10+Math.floor(Math.random()*16),vy:1.4+Math.random()*1.5+run.wave*0.08})}
function spawnDrone(){const fromLeft=Math.random()<0.5;run.drones.push({x:fromLeft?-24:744,y:50+Math.random()*250,size:18,vx:fromLeft?(1.8+Math.random()*1.5+run.wave*0.08):-(1.8+Math.random()*1.5+run.wave*0.08),pulse:Math.random()*Math.PI*2})}
function bankCargo(){if(!run||!run.active)return;if(run.cargoHeld<=0){ui.banner.className="result-banner neutral";ui.banner.textContent="No cargo to bank yet.";return}const earned=run.cargoHeld*18;profile.credits+=earned;profile.bestRun=Math.max(profile.bestRun,profile.credits);logEvent(`Banked ${run.cargoHeld} cargo for ${earned} credits.`,"good");run.cargoHeld=0;ui.banner.className="result-banner win";ui.banner.textContent=`Cargo secured. +${earned} credits to your ship account.`;saveProfile();renderHud()}
function repairHull(){if(!run||!run.active)return;const missing=run.hullMax-run.hull;if(missing<=0)return;const cost=missing*12;if(profile.credits<cost){ui.banner.className="result-banner lose";ui.banner.textContent="Not enough credits to repair the hull.";return}profile.credits-=cost;run.hull=run.hullMax;saveProfile();logEvent(`Hull repaired for ${cost} credits.`,"warn");renderHud()}
function buyUpgrade(kind,baseCost){const level=profile.upgrades[kind];const cost=baseCost+(level-1)*40;if(profile.credits<cost){ui.banner.className="result-banner lose";ui.banner.textContent="Not enough credits for that upgrade.";return}profile.credits-=cost;profile.upgrades[kind]+=1;saveProfile();ui.banner.className="result-banner win";ui.banner.textContent=`${kind} upgraded to level ${profile.upgrades[kind]}.`;logEvent(`${kind} upgraded.`,"good");renderHud()}
function overlaps(a,b){return a.x<b.x+b.size&&a.x+a.size>b.x&&a.y<b.y+b.size&&a.y+a.size>b.y}
function endRun(reason){if(!run)return;run.active=false;profile.bestRun=Math.max(profile.bestRun,profile.credits);saveProfile();ui.banner.className="result-banner lose";ui.banner.textContent=reason;logEvent(reason,"bad");renderHud()}
function update(){if(!run||!run.active)return;run.ticks++;if(run.ticks%280===0){run.wave++;logEvent(`Pressure wave ${run.wave} incoming.`,"warn")}run.oxygen-=0.045+run.wave*0.002;const p=run.player;if(keys["ArrowLeft"]||keys["a"])p.x-=p.speed;if(keys["ArrowRight"]||keys["d"])p.x+=p.speed;if(keys["ArrowUp"]||keys["w"])p.y-=p.speed;if(keys["ArrowDown"]||keys["s"])p.y+=p.speed;p.x=Math.max(10,Math.min(690,p.x));p.y=Math.max(10,Math.min(390,p.y));if(Math.random()<0.04+run.wave*0.002)spawnScrap();if(Math.random()<0.018+run.wave*0.0015)spawnDrone();run.scrap.forEach(s=>s.y+=s.vy);run.drones.forEach(d=>{d.x+=d.vx;d.pulse+=0.08;d.y+=Math.sin(d.pulse)*0.7});run.scrap=run.scrap.filter(s=>{if(overlaps(p,s)){if(run.cargoHeld<run.cargoMax){run.cargoHeld++;profile.credits+=s.value;logEvent(`Recovered scrap worth ${s.value} credits.`,"good");saveProfile();return false}else{ui.banner.className="result-banner neutral";ui.banner.textContent="Cargo full. Bank salvage before collecting more."}}return s.y<450});run.drones=run.drones.filter(d=>{if(overlaps(p,d)){run.hull-=1;if(run.cargoHeld>0&&Math.random()<0.5)run.cargoHeld--;ui.banner.className="result-banner lose";ui.banner.textContent="Drone strike! Hull damage taken.";logEvent("Drone strike. Hull damaged.","bad");return false}return d.x>-40&&d.x<760});if(run.oxygen<=0)endRun("Oxygen depleted. The run is over.");if(run.hull<=0)endRun("Hull failure. The salvage ship breaks apart.")}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!run){ctx.fillStyle="#9fb0d1";ctx.font="20px Inter, sans-serif";ctx.fillText("Start a new run to begin salvaging.",200,220);return}ctx.fillStyle="#eaf2ff";run.stars.forEach(s=>{ctx.globalAlpha=.45;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;ctx.strokeStyle="rgba(125,211,252,.18)";ctx.strokeRect(10,10,700,400);ctx.fillStyle="#7dd3fc";ctx.fillRect(run.player.x,run.player.y,run.player.size,run.player.size);ctx.fillStyle="#fbbf24";run.scrap.forEach(s=>ctx.fillRect(s.x,s.y,s.size,s.size));ctx.fillStyle="#fb7185";run.drones.forEach(d=>{ctx.beginPath();ctx.arc(d.x,d.y,d.size/2,0,Math.PI*2);ctx.fill()});ctx.fillStyle="#cbd5e1";ctx.font="14px Inter, sans-serif";ctx.fillText("Bank Zone",16,32);ctx.strokeStyle="rgba(52,211,153,.4)";ctx.strokeRect(10,350,90,60)}
function renderHud(){ui.credits.textContent=profile.credits;ui.best.textContent=profile.bestRun;ui.cargoUpgrade.textContent=profile.upgrades.cargo;ui.speedUpgrade.textContent=profile.upgrades.speed;ui.hullUpgrade.textContent=profile.upgrades.hull;if(!run){ui.oxygen.textContent="—";ui.cargo.textContent="0/0";ui.hull.textContent="—";ui.wave.textContent="—"}else{ui.oxygen.textContent=Math.max(0,run.oxygen).toFixed(1);ui.cargo.textContent=`${run.cargoHeld}/${run.cargoMax}`;ui.hull.textContent=`${Math.max(0,run.hull)}/${run.hullMax}`;ui.wave.textContent=run.wave}}
function loop(){update();draw();renderHud();requestAnimationFrame(loop)}
document.addEventListener("keydown",e=>keys[e.key]=true);document.addEventListener("keyup",e=>keys[e.key]=false);startRunBtn.addEventListener("click",startRun);bankCargoBtn.addEventListener("click",bankCargo);repairBtn.addEventListener("click",repairHull);upgradeCargoBtn.addEventListener("click",()=>buyUpgrade("cargo",60));upgradeSpeedBtn.addEventListener("click",()=>buyUpgrade("speed",70));upgradeShieldBtn.addEventListener("click",()=>buyUpgrade("hull",80));
renderHud();loop();
